# Generated by Django 5.2.7 on 2025-11-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
